slug: ai-expo-korea-2026
date: 2026-05-06
date_end: 2026-05-08
title: AI EXPO KOREA 2026
subtitle: 국제인공지능대전
type: exhibition
location: 서울 COEX 1층 Hall A
organizer:
  - (사)한국인공지능협회
  - (주)서울메쎄
  - 인공지능신문
audience: B2B
url:
tags:
  - ai
  - exhibition
  - b2b
  - expo

